### ISSUE TITLE
меню на экране sm 

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#13]
На эране шириной sm (768-991) строка с телефоном отображается в самом верху, строка с пунктами меню верхнего уровня перемещается под строку с логотипом:

https://github.com/StarLinkProj/StarLink/issues/4

**Comment by maoizm** [comment]
@StarLinkProj  задание по дизайну меню для экрана sm [отработано](https://github.com/StarLinkProj/StarLink/issues/4)  , файлы лежат в https://drive.google.com/drive/folders/0B5-5GS0I19q9dnY1Y2x1MGM1c1k

**Comment by StarLinkProj** [comment]
Зробив. Коли екран менше 767, тоді треба вмикати режим мобільного перегляду, оскільки браузер тоді не відображає реального стану об’єктів ДОМ дерева
