### ISSUE TITLE
меню на экране xs ( <768 px)

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#14]
реализовать отображение и поведение меню в соответствии с законченным дизайном
https://github.com/StarLinkProj/StarLink/issues/2

**Comment by maoizm** [comment]
задание по дизайну меню для экрана xs [отработанj](https://github.com/StarLinkProj/StarLink/issues/4)  , файлы лежат в https://drive.google.com/drive/folders/0B5-5GS0I19q9dnY1Y2x1MGM1c1k

**Comment by StarLinkProj** [comment]
Зробив!
