### ISSUE TITLE
Съезжает текст на hero images при сужении экрана

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#15]

**Comment by Vitold55** [comment]
не розумію де це. 
Кинь посилання сторінки!

**Comment by maoizm** [comment]
![image](https://cloud.githubusercontent.com/assets/5243590/17919922/c8e5c146-69d9-11e6-8404-7609af562989.png)

**Comment by Vitold55** [comment]
Поправив

**Comment by maoizm** [comment]
текст перестал съезжать, но получается совсем другое форматирование при сужении экрана до xs:

![image](https://cloud.githubusercontent.com/assets/5243590/18006804/27653f40-6baa-11e6-9174-8168e2f50b09.png)

**Comment by Vitold55** [comment]
ok. Поправлю

**Comment by StarLinkProj** [comment]
Пофіксив
