### ISSUE TITLE
дизайн меню на мобилке

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#2]
что-то мне не нравится как выглядит меню на узком экране.
имхо слишком много пустого места.  кнопку выпадения меню наверное логично сделать на одно уровне с лого?

и телефон на узком экране выглядит гигантским

![скриншот](http://i.imgur.com/ej0xG36.png)

**Comment by artchernikoff** [comment]
Меню нужно трансформировать в toggle menu
(html - https://drive.google.com/open?id=0B5-5GS0I19q9MTVHVWtPRHpJTnM)
![mobile - menu open](https://cloud.githubusercontent.com/assets/11192987/17617871/10d0020e-6085-11e6-9275-2afc42d7f168.jpg)
![mobile - menu](https://cloud.githubusercontent.com/assets/11192987/17617870/10d015fa-6085-11e6-9c9c-32406e41fda8.jpg)

**Comment by StarLinkProj** [comment]
Зробив. Протесть!
