### ISSUE TITLE
добавить черную тень на белый текст на hero images

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#24]
надо добавить черную тень вокруг белых букв на hero images,  что-то типа  `text-shadow: 0 0 4px #303030;`   

иначе на белых участках картинок белый текст становится неразличим:

http://starlink.pp.ua/

![image](https://cloud.githubusercontent.com/assets/5243590/18007249/e89dde14-6bab-11e6-9084-ce185a60e48d.png)

**Comment by Vitold55** [comment]
Зробив
