### ISSUE TITLE
добавления к калькулятору №5

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#25]
нужно добавить текст (SLA 1, SLA 2, SLA 3) к первой колонке калькулятора и заглавие к ней:

![calculator](https://cloud.githubusercontent.com/assets/5243590/18009441/f1697658-6bb4-11e6-8185-9d0707da9911.png)

иконка: 
![sla-icon](https://cloud.githubusercontent.com/assets/5243590/18009479/1ca68efa-6bb5-11e6-8490-bfba084ffdee.png)

**Comment by StarLinkProj** [comment]
Зробив
