### ISSUE TITLE
кнопка и строка поиска

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#3]
не вижу реализации поисковой строки, в дизайне было такое:

![image](http://i.imgur.com/x1zragO.png)

и такое:
![строка поиска](http://i.imgur.com/2gjnklw.png?1)

**Comment by artchernikoff** [comment]
Поисковая строка появляется поверх меню при состоянии active как в дизайне, пример реализации - http://totaltheme.wpengine.com/nouveau/
