### ISSUE TITLE
меню на планшете <1024 px wide

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#4]
на этой ширине над меню нужно тоже поработать: не годится

![ ](http://i.imgur.com/DjNvxfF.png)

**Comment by artchernikoff** [comment]
Телефон уходит на верхнюю плашку как на мобильном. Если текстовое меню помещается целиком - то отображается, если нет, наследует дизайн мобильного и становиться toggle меню. Возможно там следует продумать другой перечень, чтобы избавиться от подкатегорий
![mobile - menu open](https://cloud.githubusercontent.com/assets/11192987/17618050/251f3972-6086-11e6-9caf-447574bb7d61.jpg)

**Comment by maoizm** [comment]
проверил, как помещается меню на экранах различной ширины - меню помещается на всех экранах, кроме xs (<768 px).  На экране sm (768-991 px) строку меню нужно убирать под строку с логотипом и телефоном.

полностью все детали поведения меню здесь:
https://drive.google.com/open?id=1-0MkXHp9vDpnKoH_nkiryZ7tTwO3PkMJiYCzoycjYsE

**Comment by maoizm** [comment]
@artchernikoff проверил предлагаемый дизайн на экране шириной от 768 до 991 пикселов (то, что движок отображает на планшетах). Логотип и меню вполне помещаются в строке, не виєу смысла в кнопке включения/выключения меню. А вот телефон при этом не помещается, и смущает что на экране шириной ближе к верхней границе диапазона черная строка с телефоном становится чересчур большой.  

768px wide:
![image](https://cloud.githubusercontent.com/assets/5243590/17798555/ddbdfb4a-65da-11e6-8b33-747f722a64bd.png)

991px:  ![am-sm-menu-991](https://cloud.githubusercontent.com/assets/5243590/17798641/adb09e02-65db-11e6-80fe-eb7a834f7692.png)

детали желаемого поведения меню описал здесь: https://drive.google.com/open?id=1-0MkXHp9vDpnKoH_nkiryZ7tTwO3PkMJiYCzoycjYsE

**Comment by artchernikoff** [comment]
Добавил меню для планшета - https://drive.google.com/drive/folders/0B5-5GS0I19q9dnY1Y2x1MGM1c1k?usp=sharing

![menu tablet](https://cloud.githubusercontent.com/assets/11192987/17803142/2cf9604c-65fd-11e6-8a91-1015642c7dcb.jpg)

![menu tablet open](https://cloud.githubusercontent.com/assets/11192987/17803144/3460c60e-65fd-11e6-8854-56c85aecf6fd.jpg)
