### ISSUE TITLE
дизайн страницы блога

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#5]
под блог дизайн новостной страницы не годится - нужен более простой линейный дизайн ленты блога, сжать до минимума верхнее меню, убрать большой блок кнопок с услугами внизу.
под верхним меню добавить однустроку элементов навигации по блогу: по тегам, датам (последний месяц / 3 месяца / год)

**Comment by artchernikoff** [comment]
Доработал дизайн блога
https://drive.google.com/open?id=0B5-5GS0I19q9V0VjSHdmOC04Skk

![default](https://cloud.githubusercontent.com/assets/11192987/17803917/ec5c4ebe-6601-11e6-8574-88886c44fe1f.jpg)
