### ISSUE TITLE
футер плохо себя ведет на узких экранах - нужно нарисовать красиво

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#6]
вот:

![вот](http://i.imgur.com/m6hdhST.png)

и вот:

![вот](http://i.imgur.com/GlfG0Dt.png)

**Comment by artchernikoff** [comment]
элементы в футере на мобильном должны выстраиваться по центру, а также некоторые шрифты заглавий должны уменьшиться по сравнению с веб версией
(html - https://drive.google.com/open?id=0B5-5GS0I19q9WUlrZW4yY2JRRmM)
![mobile - footer](https://cloud.githubusercontent.com/assets/11192987/17618567/296f3236-6089-11e6-8b15-00f7c161970b.png)

**Comment by maoizm** [comment]
принято
