### ISSUE TITLE
исправления в калькуляторе услуг №1

### ISSUE THREAD

**Issue by maoizm** [StarLinkProj/StarLink#8]
![image](https://cloud.githubusercontent.com/assets/5243590/17728409/c19d56aa-6467-11e6-93ea-bdf5e684b97a.png)

заменить "количество серверов" на "количество физических серверов", "из них виртуальных " на "количество вирутальных серверов"

**Comment by Vitold55** [comment]
Зробив

**Comment by maoizm** [comment]
+
